apiVersion: v1
kind: Service
metadata:
  name: miporin
  namespace: knative-serving
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 18080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: miporin-localdev
  namespace: knative-serving
  labels:
    kubernetes.io/service-name: miporin
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 18080
endpoints:
  - addresses:
    - "192.168.122.100"
---
